export enum StockMovementType {
  INCOME = 'INCOME',
  SALE = 'SALE',
  MANUAL_ADJUSTMENT = 'MANUAL_ADJUSTMENT',
  SALE_CANCEL = 'SALE_CANCEL',
  INCOME_CANCEL = 'INCOME_CANCEL',
  TO_RESERVE = 'TO_RESERVE',
  FROM_RESERVE = 'FROM_RESERVE',
  KILN_IN_RAW = 'KILN_IN_RAW',
  KILN_OUT_BAKED = 'KILN_OUT_BAKED',
  RAW_PRODUCTION = 'RAW_PRODUCTION',
  PREPAYMENT_DELIVERY = 'PREPAYMENT_DELIVERY',
}
