export enum WorkerPaymentCategory {
  HUMBUZ_KIRDI_CHIQDI = 'HUMBUZ_KIRDI_CHIQDI',
  HUMBUZ_ESHIKCHI = 'HUMBUZ_ESHIKCHI',
  PRESS = 'PRESS',
  FIELD_RAW_LOADING = 'FIELD_RAW_LOADING',
  RESERVE_RAW_LOADING = 'RESERVE_RAW_LOADING',
  RESERVE_BAKED_LOADING = 'RESERVE_BAKED_LOADING',
  ROAD_PAYMENT = 'ROAD_PAYMENT',
  ADVANCE = 'ADVANCE',
  OTHER = 'OTHER',
}
