export enum WorkerPaymentCategory {
  HUMBUZ_KIRDI_CHIQDI = 'HUMBUZ_KIRDI_CHIQDI',
  HUMBUZ_ESHIKCHI = 'HUMBUZ_ESHIKCHI',
  QACHIGAR = 'QACHIGAR',
  PRESS = 'PRESS',
  FIELD_RAW_LOADING = 'FIELD_RAW_LOADING',
  RESERVE_RAW_LOADING = 'RESERVE_RAW_LOADING',
  RESERVE_BAKED_LOADING = 'RESERVE_BAKED_LOADING',
  ROAD_PAYMENT = 'ROAD_PAYMENT',
  KRETKACHI = 'KRETKACHI',
  ESHKI = 'ESHKI',
  ADVANCE = 'ADVANCE',
  OTHER = 'OTHER',
}
